# Generated by Django 4.1.3 on 2022-11-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
