# Generated by Django 4.1.3 on 2022-11-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_manager_api', '0003_alter_todo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.FileField(blank=True, max_length=3000, null=True, upload_to=''),
        ),
    ]
