---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myredis
  labels:
    app: myredis-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: myredis
  template:
    metadata:
      labels:
        app: myredis
    spec:
      containers:
        - name: myredis
          image: redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379

          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: myredis-pvc