# Generated by Django 4.1.3 on 2022-11-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_manager_api', '0005_ad_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.AlterField(
            model_name='ad',
            name='state',
            field=models.CharField(blank=True, default='in progress', max_length=50, null=True),
        ),
    ]
