# Generated by Django 4.1.3 on 2022-11-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_manager_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
